export const INITIALIZE = 'APP:INITIALIZE';
export const INITIALIZED = 'APP:INITIALIZED';
export const LOADING_START = 'APP:LOADING:START';
export const LOADING_STOP = 'APP:LOADING:STOP';
export const GET_DEVICE_DETAILS = 'APP:GET:DEVICE:DETAILS';
export const GET_DEVICE_DETAILS_SUCCESS = 'APP:GET:DEVICE:DETAILS:SUCCESS';
export const GET_DEVICE_DETAILS_FAILURE = 'APP:GET:DEVICE:DETAILS:FAILURE';

export const initialize = () => ({
  type: INITIALIZE,
});
